---
title: "rename_out_table_for_metadata_table"
author: "Marly"
date: "2025-03-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load required libraries
library(readxl)
library(dplyr)


counts_barcodes_original <- read.delim("/Users/u_erazo/Documents/GitHub/Namibia_project/Data/16S/processed_data/EMU_output/stardard/combine_outputs_standard/emu-combined-abundance-tax_id-counts.tsv", sep = "\t", header = TRUE, check.names = FALSE)

names(counts_barcodes_original) <- gsub("\\.", "-", names(counts_barcodes_original))

reference_file <- path.expand("/Users/u_erazo/Documents/GitHub/Namibia_project/Data/16S/reference_files/reference_file.csv")

```


```{r}
# Check if the file exists
if (!file.exists(counts_barcodes_original)) {
  stop(paste("File not found:", counts_barcodes_original))
}

# Load the reference file
df_reference <- read.csv(reference_file)

# Create a mapping dictionary for column names
mapping_names <- setNames(df_reference$sample_names, df_reference$barcode)

# Load the data file
df_data <- read.delim(counts_barcodes_original,  header = TRUE)

# Rename columns based on the mapping dictionary
new_column_names <- c("tax_id", sapply(names(df_data)[-1], function(col) ifelse(col %in% names(mapping_names), mapping_names[col], col)))
names(df_data) <- new_column_names

# Save the modified file
write.table(df_data, "/Users/u_erazo/Documents/GitHub/Namibia_project/Data/16S/phyloseq_elements/otu_table.tsv", sep = "\t", row.names = FALSE, quote = FALSE)

```
```{r}
# Prüfen, welche Spaltennamen existieren
print("Column names in df_data:")
print(names(df_data))

print("Barcodes in df_reference:")
print(names(mapping_names))

```

