---
title: "Nanodrop_data_management"
author: "Fay"
date: "2023-03-26"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
# install libraries
library(dplyr)
library(XML)
library(methods)
library(plyr)
library(readr)
library(ggplot2)
```

## Read the tsv nanodrop and write them as csv
### David
```{r, message = FALSE, warning = FALSE}
#read tsv table
David <- read_tsv("~/GitHub/Namibia_project/Data/Nanodrop_measurements/David_Nanodrop_DNA-Extractions.tsv")

# remove ffirst column
David <-  David[,-1]

#add column sample type
David <- David %>% 
    mutate(animal = "David")

#change the column names

write.csv(David, 
          "~/GitHub/Namibia_project/Data/Nanodrop_measurements/CSV/David.csv",
          row.names = FALSE)
```


### Düppel

```{r, message = FALSE, warning = FALSE}
#read tsv table
Duppel_1 <- read_tsv("~/GitHub/Namibia_project/Data/Nanodrop_measurements/Düppel_26022023_2.tsv")

# remove ffirst column
Duppel_1 <-  Duppel_1[,-1]


#change the column names

write.csv(Duppel_1, 
          "~/GitHub/Namibia_project/Data/Nanodrop_measurements/CSV/Düppel_26022023.csv",
          row.names = FALSE)
```

### Rodents

```{r, message = FALSE, warning = FALSE}
#read tsv table
Rodent_1 <- read_tsv("~/GitHub/Namibia_project/Data/Nanodrop_measurements/Rodents_26032023.tsv")
Rodent_2 <- read_tsv("~/GitHub/Namibia_project/Data/Nanodrop_measurements/Rodents_27032023.tsv")

#combine the measuerements
Rodent <- rbind(Rodent_1,Rodent_2)

# remove first column
Rodent <-  Rodent[,-1]


write.csv(Rodent, 
          "~/GitHub/Namibia_project/Data/Nanodrop_measurements/CSV/Nano_ticks_rode_other_26032023.csv",
          row.names = FALSE)
```


## Merging the tables

```{r}
Nanodrop <- rbind(Duppel_1, Rodent)


# remove spaces
colnames(Nanodrop) <- gsub(" ", "_", colnames(Nanodrop))

# add a column to desvribe if nanodrop sample is treated with proteinase K
Nanodrop <- Nanodrop %>%
    dplyr::mutate(Proteinase_K = FALSE)


#  sample 3 LJ-001+
Nanodrop[2,1]  <- "LJ-001+"

# add the treatment of samples with proteinase k
Nanodrop[1:4, 12] <- TRUE
 

Nanodrop <- Nanodrop %>%
    dplyr::rename(Quality_260_280 = '260/280',
                  Quality_260_230 = '260/230')
```


## Assessing the quality of the DNA

```{r}
ggplot(Nanodrop, aes(x = Nucleic_Acid, y = Quality_260_280)) +
    geom_jitter() +
    labs(x = "Concentration of DNA in ng/µl", y = "Quality of DNA 260/280 ratio", 
         title = "Assessing quality of DNA with Nanodrop") 
    
```
Let's filter out the samples with eextremely high ratios

```{r}
           
ggplot(Nanodrop %>%
    filter(Quality_260_280 < 2.5,  Quality_260_280 > 1.5 ),
    aes(x = Nucleic_Acid, y = Quality_260_280)) +
    geom_jitter() +
    labs(x = "Concentration of DNA in ng/µl", y = "Quality of DNA", 
         title = "Assessing quality of DNA with Nanodrop") 
```


Assesing the quality of 260/230

```{r}
           
ggplot(Nanodrop,
    aes(x = Nucleic_Acid, y = Quality_260_230)) +
    geom_jitter() +
    labs(x = "Concentration of DNA in ng/µl", y = "Quality of DNA, 260/230", 
         title = "Assessing quality of DNA with Nanodrop") 
```


```{r}
           
ggplot(Nanodrop %>% filter(Quality_260_230 < 60), 
    aes(x = Nucleic_Acid, y = Quality_260_230)) +
    geom_jitter() +
    labs(x = "Concentration of DNA in ng/µl", y = "Quality of DNA, 260/230", 
         title = "Assessing quality of DNA with Nanodrop") 
```


```{r}
           
ggplot(Nanodrop %>%
    filter(Quality_260_230 < 2.5, Quality_260_230 > 1.8), 
    aes(x = Nucleic_Acid, y = Quality_260_230)) +
    geom_jitter() +
    labs(x = "Concentration of DNA in ng/µl", y = "Quality of DNA, 260/230", 
         title = "Assessing quality of DNA with Nanodrop") 
```


Select the samples having the golden ratios

```{r}
Nanodrop %>%
    filter( Quality_260_280 < 2.5,  Quality_260_280 > 1.5 )
```


