---
title: "Integration of OTU and EMU Taxonomic Tables into Phyloseq Object for Advanced Analysis with R"
Compailed by: Marly Erazo
Date: 06.08.24
output: html_document
df_print: paged
---

##1.Preprocess of the data to have a phyloseq object
```{r}
getwd()

list.files("..")

# Listar archivos en la subcarpeta "tables"
print(list.files("../tables"))

# Leer el archivo CSV
df <- read.csv("../tables/OTU_table.csv")

```

Fill with zeros the NA in the OTU table if necessary
```{r}

# Reemplaza los valores faltantes con ceros
df[is.na(df)] <- 0

# Guarda el data frame actualizado como un archivo CSV en el mismo directorio
write.csv(df,  "../tables/OTU_table_0.csv", row.names = FALSE)

 #make sure the counts are integer numbers. Here I prefer to go to the OTU_table and remove the zeros after the dot with excel's "replace" function (find: .*, replace: ). On the other hand you have to make sure that the metadata table has the same name as the name of the columns of the otu-table.

```


```{r}
# read in otu table and taxa table as matrix, 
# keep headers and label the rows by OTU ID (this column name should be empty)

otu.file.matrix<- as.matrix(read.table("../tables/OTU_table_0.csv", 
                              header = TRUE, sep = ",", skip = 0, row.names = 1))

tax.file.matrix<- as.matrix(read.table("../processed_data/emu-combined-taxonomy-tax_id.csv", 
                               header = TRUE, sep = ",", skip = 0, row.names = 1))
```

```{r}
# import a mapping file (sample info)
map_file <- paste("../tables/metadata.csv", sep = ",")
sampledata <- read.csv(map_file, row.names = 1)

```

```{r}
# load as phyloseq format 
library(phyloseq)

OTU = otu_table(otu.file.matrix, taxa_are_rows = TRUE)
TAX = tax_table(tax.file.matrix)
SAM = sample_data(sampledata)

```

```{r}
# load into phyloseq and save it!

physeq = phyloseq(OTU, TAX, SAM)

abundance_matrix <- as.matrix(otu_table(physeq))
# Convert the abundance matrix to integer values (if not already)
abundance_matrix <- round(abundance_matrix)

# Create a new OTU table with the abundance matrix
new_otu_table <- otu_table(physeq)
new_otu_table[, ] <- abundance_matrix

# Replace the OTU table in the phyloseq object with the new OTU table
physeq@otu_table <- new_otu_table

# Print the modified phyloseq object
print(physeq)


 saveRDS(physeq,"../phyloseq/Namibia_samples.rds")

```
